language: python

python:
  - "2.7"
  - "3.6"
  - "3.7-dev"
  # PyPy versions
  - "pypy2.7"
  - "pypy3.5"

dist: trusty
sudo: false

virtualenv:
  system_site_packages: true

addons:
  apt:
    packages:
    - python-scipy
    - time

install:
  - pip install .
  - pip install coveralls

# command to run tests
script: nosetests --with-coverage --cover-package=rebench

after_success:
  coveralls
